import { defineField, defineType } from 'sanity'

export const siteSettingsType = defineType({
  name: 'siteSettings',
  title: 'Inhalte',
  type: 'document',
  groups: [
    { name: 'welcome', title: 'Willkommen' },
    { name: 'about', title: 'Über mich' },
    { name: 'kunsttherapie', title: 'Kunsttherapie' },
    { name: 'session', title: 'Rahmenbedingungen & Preise' },
  ],
  fields: [
    // ── Willkommen ──────────────────────────────────────────────────────────
    defineField({
      name: 'welcomeIntro',
      title: 'Begrüßungstext',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'welcome',
      description: 'Der Einleitungstext unter „Willkommen".',
    }),
    defineField({
      name: 'welcomeImage',
      title: 'Willkommen – Bild',
      type: 'image',
      options: { hotspot: true },
      group: 'welcome',
      description: 'Das Bild mit den Händen/gelben Elementen.',
    }),

    // ── Über mich ──────────────────────────────────────────────────────────
    defineField({
      name: 'aboutParagraph1',
      title: 'Einleitung & Kindheit',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'about',
      description: 'Erster Abschnitt – Kindheit, Argentinien, Ecuador, Psychologiestudium.',
    }),
    defineField({
      name: 'aboutParagraph2',
      title: 'Reise nach Indien & Schlüsselmoment',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'about',
      description: 'Zweiter Abschnitt – Indienreise und Weg zur Kunsttherapie.',
    }),
    defineField({
      name: 'aboutParagraph3',
      title: 'Ausbildung & Heutige Arbeit',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'about',
      description: 'Dritter Abschnitt – Berlin, Ausbildung, Sterbebegleitung, Vision.',
    }),
    defineField({
      name: 'aboutPortrait',
      title: 'Über mich – Portrait',
      type: 'image',
      options: { hotspot: true },
      group: 'about',
      description: 'Portrait-Foto für den "Über mich"-Bereich.',
    }),

    // ── Kunsttherapie ──────────────────────────────────────────────────────
    defineField({
      name: 'ktSubtitle',
      title: 'Einleitungstext (unter dem Titel)',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'kunsttherapie',
      description: 'Der beschreibende Text direkt unter der Überschrift „Kunsttherapie".',
    }),
    defineField({
      name: 'ktHowItWorksTitle',
      title: 'Abschnittsüberschrift „Was ist Kunsttherapie?"',
      type: 'string',
      group: 'kunsttherapie',
    }),
    defineField({
      name: 'ktHowItWorksIntro',
      title: 'Erklärungstext (Was ist Kunsttherapie?)',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'kunsttherapie',
      description: 'Beschreibung was Kunsttherapie ist und was sie bewirken kann.',
    }),
    defineField({
      name: 'ktPomImage',
      title: 'POM – Bild (Portraitmal-Objekt-Methode)',
      type: 'image',
      options: { hotspot: true },
      group: 'kunsttherapie',
    }),
    defineField({
      name: 'ktPomTitle',
      title: 'POM – Methodenname',
      type: 'string',
      group: 'kunsttherapie',
    }),
    defineField({
      name: 'ktPomIntro',
      title: 'POM – Einleitungssatz',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'kunsttherapie',
      description: 'Kurzer Einleitungstext zur POM-Methode.',
    }),
    defineField({
      name: 'ktPomDescription',
      title: 'POM – Methodenbeschreibung',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'kunsttherapie',
      description: 'Ausführliche Beschreibung der Portraitmalen-Objekt-Methode.',
    }),

    // ── Rahmenbedingungen & Preise ─────────────────────────────────────────
    defineField({
      name: 'sessionDescription1',
      title: 'Ort & Setting',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'session',
      description: 'Wo finden die Sitzungen statt? (Thinkfarm, Coachingraum, …)',
    }),
    defineField({
      name: 'sessionDescription2',
      title: 'Rahmen & Materialien',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'session',
      description: 'Beschreibung des geschützten Rahmens und der verwendeten Materialien.',
    }),
    defineField({
      name: 'sessionDescription3',
      title: 'Prozessdauer & Verlauf',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'session',
      description: 'Wie lange dauert ein Prozess? Wie wird der Umfang abgestimmt?',
    }),
    defineField({
      name: 'sessionDescription4',
      title: 'Erstgespräch & Ablauf',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'session',
      description: 'Wie läuft das erste Kennenlernen ab? Dauer, Ablauf, Fragen.',
    }),
    defineField({
      name: 'sessionDescription5',
      title: 'Sitzungsdauer wählen',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'session',
      description: 'Entscheidung nach der ersten Sitzung: 60 oder 90 Minuten.',
    }),
    defineField({
      name: 'sessionRoomImage',
      title: 'Rahmenbedingungen – Raumfoto',
      type: 'image',
      options: { hotspot: true },
      group: 'session',
    }),

    // ── Preise & Abrechnung ────────────────────────────────────────────────
    defineField({
      name: 'sessionPricesTitle',
      title: 'Preise – Abschnittsüberschrift',
      type: 'string',
      group: 'session',
      initialValue: 'Preise',
    }),
    defineField({
      name: 'sessionPricesContent',
      title: 'Preise – Inhalt',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'session',
      description: 'Einzelsitzung 60/90 Min., Starterpaket, Hinweis auf Ermäßigung.',
    }),
    defineField({
      name: 'sessionBillingTitle',
      title: 'Abrechnung – Abschnittsüberschrift',
      type: 'string',
      group: 'session',
      initialValue: 'Abrechnung und Kostenübernahme',
    }),
    defineField({
      name: 'sessionBillingContent',
      title: 'Abrechnung – Inhalt',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'session',
      description: 'Privat, gesetzliche Kassen, private Zusatzversicherungen.',
    }),
    defineField({
      name: 'sessionAdvantagesTitle',
      title: 'Vorteile – Abschnittsüberschrift',
      type: 'string',
      group: 'session',
      initialValue: 'Was sind die Vorteile einer selbst bezahlten Therapie?',
    }),
    defineField({
      name: 'sessionAdvantagesContent',
      title: 'Vorteile – Inhalt (Aufzählung)',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'session',
      description: 'Am besten als Aufzählung (Bullet List) formatieren.',
    }),
    defineField({
      name: 'sessionCancellationTitle',
      title: 'Absage – Abschnittsüberschrift',
      type: 'string',
      group: 'session',
      initialValue: 'Absage',
    }),
    defineField({
      name: 'sessionCancellationContent',
      title: 'Absage – Inhalt',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'session',
      description: 'Stornierungsfristen und Bedingungen.',
    }),
    defineField({
      name: 'sessionDisclaimerTitle',
      title: 'Hinweis – Überschrift',
      type: 'string',
      group: 'session',
      initialValue: 'Hinweis zur Therapie / Haftungsausschluss',
    }),
    defineField({
      name: 'sessionDisclaimerContent',
      title: 'Hinweis – Text',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'session',
      description: 'Kleiner Haftungsausschluss am Ende des Abschnitts.',
    }),
  ],
  preview: {
    prepare: () => ({ title: 'Inhalte' }),
  },
})
